# Site wide configuration

title: "AVFLOSS"
description: "Grupo de creación y experimentación audiovisual con software libre."
logo: "logoTw.png" # 120x120 px default image used for Twitter summary card
teaser: "summaryCard.png" # 400x250 px default teaser image used in image archive grid
locale: en
#lang: en
#url: http://127.0.0.1:4000
url : https://avfloss.github.io
feed:
  path: atom.xml

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed


# Site owner
owner:
  name: "avfloss"
  email: avfloss-team@protonmail.com
  twitter: avfloss  
  google:
    ad-client:
    ad-slot:
  bio: 
  avatar: bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname:


include:
  - .htaccess
  - _pages
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
